name: CI

on:
  pull_request:
    branches:
      - master # Adjust to your branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 11
          distribution: oracle
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Build and test with Maven (contract)
        run: mvn -f Module1/pom.xml clean test

      - name: Build and test with Maven (manager)
        run: mvn -f module2/pom.xml clean test

      - name: Generate Jacoco Report (aggregate)
        run: mvn verify -DskipTests

      - name: Upload Jacoco Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco-aggregate/index.html

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.1
        with:
            path: ${{ github.workspace }}/target/site/jacoco-aggregate/index.html
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 80
            min-coverage-changed-files: 60
            title: ':lobster: Coverage Report'
            update-comment: true
            debug-mode: false
            pass-emoji: ':green_circle:'
            fail-emoji: ':red_circle:'

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
              core.setFailed('Overall coverage is less than 80%!')
