name: CI Test Result

on:
  pull_request:
    branches:
      - master # Adjust to your branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Build and test with Maven (contract)
        run: mvn -f Module1/pom.xml clean test

      - name: Build and test with Maven (manager)
        run: mvn -f module2/pom.xml clean test
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
           files: |
            ${{github.workspace}}/Module1/target/surefire-reports/*.xml
            ${{github.workspace}}/module2/target/surefire-reports/*.xml
